sudo: false

language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip
  - sudo pip3 install sqflint

script:
  - sqflint -d Missionframework

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.zip
  skip_cleanup: true
  on:
    tags: true

before_deploy:
  - cd _tools
  - npm install
  - npx gulp
  - echo "Listing built files"
  - ls ./build/
